version: 2
jobs:
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace && touch output.txt
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-flask:ci .
      - run: docker save -o my_workspace/abhinav-alpine.tar abhinav-alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
               - out
