version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace && touch output.txt
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-alpine:ci .
      - run: docker run -it --name myalpine abhinav-alpine:ci sh
      - run: docker run -it --net host --pid host --userns host --cap-add audit_control \
              -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
              -v /etc:/etc:ro \
              -v /usr/bin/containerd:/usr/bin/containerd:ro \
              -v /usr/bin/runc:/usr/bin/runc:ro \
              -v /usr/lib/systemd:/usr/lib/systemd:ro \
              -v /var/lib:/var/lib:ro \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              --label docker_bench_security \
              docker/docker-bench-security


