version: 2
jobs:
  buildone:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace && touch output.txt
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-flask:ci .
      - run: docker save -o my_workspace/abhinav-alpine.tar abhinav-alpine:ci
      - persist_to_workspace:
            root: my_workspace
            paths:
               - out
               - abhinav-alpine.tar
  buildtwo:
    machine: true
    steps:
      - checkout
      - attach_workspace:
            at: my_workspace
      - run: mkdir clair_config/
      - run: curl -L https://raw.githubusercontent.com/coreos/clair/master/config.yaml.sample -o clair_config/config.yaml
      - run: docker run -d -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -p 5432:5432 postgres:9.6
      - run: docker run --net=host -d -p 6060-6061:6060-6061 -v clair_config:/config quay.io/coreos/clair:latest -config=/config/config.yaml
    
workflows:
  version: 2
  docker_anchore:
    jobs:
      - buildone
      - buildtwo:
         requires:
           - buildone
